package httpserver;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    GET_EPICS,
    GET_EPIC_BY_ID,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    GET_PRIOR,
    POST_TASKS,
    POST_SUBTASKS,
    POST_EPICS,
    DELETE_TASK,
    DELETE_SUBTASK,
    DELETE_EPIC,
    UNKNOWN
}
